<?php
 
class PartTableSeeder extends Seeder {

    /*'frame' => 'Frame', 
    'fork_headset' => 'Fork/Headset',
    'crankset_bracket' => 'Crankset/Bottom Bracket',
    'pedals_straps' => 'Pedals/Straps',
    'drive_cog_chainring' => 'Drivetrain/Cog/Chainring/Chain',
    'front_hub_wheel_tire' => 'Front Wheel/Hub/Tire',
    'back_hub_wheel_tire' => 'Back Wheel/Hub/Tire',
    'brake_lever' => 'Brake/Brake Lever',
    'handlebar_stem_grip' => 'Handlebar/Grip/Stem',
    'saddle_seat' => 'Saddle/Seatpost/Clamp',
    'accessories' => 'Accessories'*/

    public function run()
    {
        ######### Username: mattpelaggi from http://www.pedalroom.com/bike/surly-steamroller-19004	    
        $part = Part::create(array(
            'type' => 'frame',
            'part_name' => '2013 Surly Steamroller 53cm',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'Surly',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'FSA Orbit X',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'SRAM Omnium',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'SRAM GXP',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'Time ATAC XS',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => '17t Surly',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => '47t Sugino 75',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'KMC Z510HX',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Nitto B260AA',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Thomson Elite X4',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Oury Grips',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Selle Italia Flite 1990',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Thomson Elite',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'brake_lever',
            'part_name' => 'Diatech Gold Finger',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'brake_lever',
            'part_name' => 'Tektro R539',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'H Plus Son TB14',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'Formula',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Vittoria Randonneur 25c',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'accessories',
            'part_name' => 'Thomson Top Cap and Seatpost Collar',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'accessories',
            'part_name' => 'Riehl Industries TCB Rack',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'accessories',
            'part_name' => 'Mirrycle Incredibell',
            'user_id' => '1'));

        ######## Username: HNFXD
        ######## From: http://www.pedalroom.com/bike/planet-x-pro-carbon-hhsb-13420
        $part = Part::create(array(
            'type' => 'frame',
            'part_name' => 'Planet X Pro Carbon Track Frame',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'Corratec Track Fork',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'FSA',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'SRAM Omnium',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'SRAM GXP',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'MKS CT-Lite Black Edition',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'Aurora Velcro Straps',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => '51x16/Dura Ace',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'Sugino Zen',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'Sram',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'KCNC',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Deda Pista 90mm',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Selle Italia SLS Kit Carbonio(stripped)',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Planet X Carbon Seatpost',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'Zipp 1080',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'Vittoria Rubino',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Vittoria Diamond Pro',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Mavic Ellipse',
            'user_id' => '2'));    
        ######## From: http://www.pedalroom.com/bike/dolan-pre-cursa-blue--18115
        $part = Part::create(array(
            'type' => 'frame',
            'part_name' => 'Dolan Pre Cursa Blue 52cm',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'Alpina',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'Stronglight 2000',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'Stronglight',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'All City',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'Aurora Velcro Straps',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => '48x17/Halo',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'SRAM Omnium',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'Sram',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Easton Monkey Bar EA50',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'FSA OS 190',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Selle San Marco Concor',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'Alpina',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'HED Jet 60',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'HED',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'Continental UltraSport 25c',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Halo Aerorage',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Halo',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Continental UltraSport 28c',
            'user_id' => '2'));

        ######## Username: JaredFaucher
        ######## From: My personal bike
        $part = Part::create(array(
            'type' => 'frame',
            'part_name' => 'Mercier Kilo Stripper Raw 50cm',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'Mercier 520 Cromly',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'fork_headset',
            'part_name' => 'Threadless 1in',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'TruVativ Tour 48T',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'crankset_bracket',
            'part_name' => 'PowerSpline',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'pedals_straps',
            'part_name' => 'Traditional Road w/ Binda Straps ',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => '16t Fixed Gear',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'drive_cog_chainring',
            'part_name' => 'KMC Gold Edition',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => '6061 Aluminum Classic Bend',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Forged Aluminum Threadless 1in',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'handlebar_stem_grip',
            'part_name' => 'Deluxe Cork',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'SLR Style Racing',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'saddle_seat',
            'part_name' => 'SL Micro Adjust',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'brake_lever',
            'part_name' => 'Front/Rear Tektro R350',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'brake_lever',
            'part_name' => 'Front/Rear Tektro RL570',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'TrackSpec High Flange',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'front_hub_wheel_tire',
            'part_name' => 'Kenda Koncept Lite',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'TrackSpec High Flange',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'back_hub_wheel_tire',
            'part_name' => 'Kenda Koncept Lite',
            'user_id' => '3'));
  	}
 
}