<?php
 
class PartTableSeeder extends Seeder {

    public function run()
    {
        ######### Username: mattpelaggi from http://www.pedalroom.com/bike/surly-steamroller-19004	    
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => '2013 Surly Steamroller 53cm',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Surly',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'FSA Orbit X',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'SRAM Omnium',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'SRAM GXP',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Time ATAC XS',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '17t Surly',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '47t Sugino 75',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'KMC Z510HX',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Nitto B260AA',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Thomson Elite X4',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Oury Grips',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Selle Italia Flite 1990',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Thomson Elite',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Brake/Brake Lever',
            'part_name' => 'Diatech Gold Finger',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Brake/Brake Lever',
            'part_name' => 'Tektro R539',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'H Plus Son TB14',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Formula',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Vittoria Randonneur 25c',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Accessories',
            'part_name' => 'Thomson Top Cap and Seatpost Collar',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Accessories',
            'part_name' => 'Riehl Industries TCB Rack',
            'user_id' => '1'));
        $part = Part::create(array(
            'type' => 'Accessories',
            'part_name' => 'Mirrycle Incredibell',
            'user_id' => '1'));

        ######## Username: HNFXD
        ######## From: http://www.pedalroom.com/bike/planet-x-pro-carbon-hhsb-13420
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => 'Planet X Pro Carbon Track Frame',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Corratec Track Fork',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'FSA',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'SRAM Omnium',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'SRAM GXP',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'MKS CT-Lite Black Edition',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Aurora Velcro Straps',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '51x16/Dura Ace',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Sugino Zen',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Sram',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'KCNC',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Deda Pista 90mm',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Selle Italia SLS Kit Carbonio(stripped)',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Planet X Carbon Seatpost',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Zipp 1080',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Vittoria Rubino',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Vittoria Diamond Pro',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Mavic Ellipse',
            'user_id' => '2'));    
        ######## From: http://www.pedalroom.com/bike/dolan-pre-cursa-blue--18115
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => 'Dolan Pre Cursa Blue 52cm',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Alpina',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'Stronglight 2000',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'Stronglight',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'All City',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Aurora Velcro Straps',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '48x17/Halo',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'SRAM Omnium',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Sram',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Easton Monkey Bar EA50',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'FSA OS 190',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Selle San Marco Concor',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Alpina',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'HED Jet 60',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'HED',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Continental UltraSport 25c',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Halo Aerorage',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Halo',
            'user_id' => '2'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Continental UltraSport 28c',
            'user_id' => '2'));

        ######## Username: JaredFaucher
        ######## From: My personal bike
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => 'Mercier Kilo Stripper Raw 50cm',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Mercier 520 Cromly',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Threadless 1in',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'TruVativ Tour 48T',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'PowerSpline',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Traditional Road w/ Binda Straps ',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '16t Fixed Gear',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'KMC Gold Edition',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => '6061 Aluminum Classic Bend',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Forged Aluminum Threadless 1in',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Deluxe Cork',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'SLR Style Racing',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'SL Micro Adjust',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Brake/Brake Lever',
            'part_name' => 'Front/Rear Tektro R350',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Brake/Brake Lever',
            'part_name' => 'Front/Rear Tektro RL570',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'TrackSpec High Flange',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Kenda Koncept Lite',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'TrackSpec High Flange',
            'user_id' => '3'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Kenda Koncept Lite',
            'user_id' => '3'));

        ######## Username: Apollinaire
        ######## From: http://www.pedalroom.com/bike/red-the-colnago-17125
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => 'Colnago 50cm',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Colnago track fork',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Chris King 2nut',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'Phil Wood Track Cranks 165mm',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'Phil Wood BB',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Shimano PD-A600',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Phil Wood 19t',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Phil Wood 48t',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Izumi Super Toughness',
            'user_id' => '4'));        
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Nitto b809aa',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Nitto Pearl',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Selle Italia SLR Gel Flow',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Thomson Elite',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'DT Swiss RR585',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Phil Wood High Flange',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Michelin Pro4',
            'user_id' => '4'));        
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'DT Swiss RR585',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Phil Wood High Flange',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Michelin Pro4',
            'user_id' => '4'));
        ######## From: http://www.pedalroom.com/bike/06-chrome-bianchi-pista-stripped-14707  	
        $part = Part::create(array(
            'type' => 'Frame',
            'part_name' => '2006 Bianchi Pista',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Lugged CroMo Fork - Reynolds 520',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Fork/Headset',
            'part_name' => 'Chris King NoThreadSet',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'SRAM Omnium 165mm',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Crankset/Bottom Bracket',
            'part_name' => 'GXP Team external BB',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Pedals/Straps',
            'part_name' => 'Shimano m520',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Phil Wood 18t cog',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => 'Phil Wood lockring',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Drivetrain/Cog/Chainring/Chain',
            'part_name' => '48t Omnium chainring',
            'user_id' => '4'));        
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Generic 20mm risers',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Handlebar/Grip/Stem',
            'part_name' => 'Easton EA 50',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Saddle/Seatpost/Clamp',
            'part_name' => 'Selle San Marco Shot Race',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Brake/Brake Lever',
            'part_name' => 'Sora',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Front Wheel/Hub/Tire',
            'part_name' => 'Mavic CXP22 road wheel',
            'user_id' => '4'));       
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Mavic Open Pro',
            'user_id' => '4'));
        $part = Part::create(array(
            'type' => 'Back Wheel/Hub/Tire',
            'part_name' => 'Phil Wood HF single fixed 28h 2-cross',
            'user_id' => '4'));
    }
}